### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by xukai92** [julia-actions/julia-uploadcoveralls#4]
I'm guessing just do `uses: julia-actions/julia-uploadcoveralls@latest`? But apparently nothing is uploaded to my Coveralls. Do I need to set anything else?

**Comment by davidanthoff** [comment]
I would actually recommend to not use this action here, but instead use the native codecov action to upload coverage reports. It doesn't require a token, so much simpler. You can take a look at [this](https://github.com/davidanthoff/StringBuilders.jl/blob/master/.github/workflows/jlpkgbutler-ci-master-workflow.yml) workflow to see a template how that might look.

**Comment by xukai92** [comment]
Thanks.  I was trying to see if I can do everything in GitHub Actions without Travis. The template helps. Thanks again!
